### PR TITLE
Create TS Sealed

### PR DESCRIPTION
**Pull request by dmasalin**
Original File Title: "Dwarves Gandalf - Sauron Grind.pack"
Deck artwork, formatted to size, attached below
dwarves gandalf - sauron grind

### CODE REVIEW

**Comment by dmasalin** [comment]
MarcinS, do I need to create a PR for every deck? Can't find a way to add multiple files into the same PR, and I didn't want to just have them consecutively in the same text file, for organization purposes.

Thanks and best regards!

dmaz

**Comment by MarcinSc** [comment]
You just do changes (commits) to your forked repo, and once you're finished just click the "Create pull request".

Alternatively, I can keep the PR open, and all the commits you do to your repo on GitHub will be added to this PR.

**Comment by dmasalin** [comment]
All Deck Files Committed.

Remaining corresponding deck artwork listed here:

Serie 1, Deck 2:
rohan allies - archery

Serie 1, Deck 3:
three hunters - uruk trackers

Serie 2, Deck 1:
knights -dunland discard

Serie 2, Deck 2:
ringbound companions - easterling gollum

Serie 2, Deck 3:
rohan gandalf - twilight nazgul

Serie 3, Deck 1:
hobbits smeagol - rohirrim traitor

Serie 3, Deck 2:
shoulder to shoulder - southrons

Serie 3, Deck 3:
unbound rangers - berserkers

**Comment by dmasalin** [comment]
This is basically everything for the TS Sealed League, other than the overarching settings for the league when it gets upload.

Boosters provided by Serie:
Serie 1: 2x The Fellowship of the Ring, 2x The Two Towers, 2x Player's Choice
Serie 2: 1x Mines of Moria, 1x Battle of Helm's Deep, 1x Player's Choice
Serie 3: 1x Realms of the Elf-lords, 1x Ents of Fangorn, 1x Player's Choice
Serie 4: 6x Player's Choice

Standard TS Rules apply (RB Skirmish can be canceled). BUT, just like Movie Sealed, NO X-list.

Thanks very much for reminding everyone of this site. I'm looking forward to helping out in any way I can.

Myself and several others have been working with the current bugs, and working with the coding, so we should have some PRs for fixes coming soon too. 

Please let me know if there's anything I've missed or anything I can do at all to make all these changes as smooth and easy for you as possible!

All the best,

dmaz

**Comment by MarcinSc** [comment]
Player's Choice is from among those in the TS, or any boosters at all?

**Comment by dmasalin** [comment]
Player's Choice would be from among those in TS. Sets 1 - 6

**Pull request merged**
